easy_admin:
    entities:
        Category:
            class: App\Entity\Category
            label: Categories
        Material:
            class: App\Entity\Material
            label: Materials
            new:
                fields: ['title', {property: 'imageFile', type: 'file'}, 'category']
            edit:
                fields: ['title', {property: 'imageFile', type: 'file'}, 'category']
        User:
            class: App\Entity\User
            label: Users